### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by Deteorek** [acc-ua/homebridge-xiaomi-humidifier#1]
Hi,
First of all, thank you very much for your hard work, unfortunately, they will not work for me. I'm still getting an error:

[11/26/2017, 9:54:44 AM] Loaded plugin: homebridge-xiaomi-humidifier
/usr/lib/node_modules/homebridge-xiaomi-humidifier/index.js:12
    this.log.debug('conf');
            ^

TypeError: Cannot read property 'debug' of undefined
    at Plugin.module.exports [as initializer] (/usr/lib/node_modules/homebridge-xiaomi-humidifier/index.js:12:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:150:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

And second what is proper name for "platform"? In exemple configuration you have
    "platform": "MiHumidiferPlatform" or it should be "MiHumidifierPlatform" with "i".

Could you give me any help?
Thanks

**Comment by Dengor1984** [comment]
Name should be "MiHumidifierPlatform" with "i"

I have the same issues...

TypeError: Cannot read property 'debug' of undefined
    at Plugin.module.exports [as initializer] (/usr/lib/node_modules/homebridge-xiaomi-humidifier/index.js:12:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:152:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:130:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:55:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by acc-ua** [comment]
yes, there was a type in the code that was fixed several days ago, but looks like I forgot to upload it to NPM. I will do that a bit later today.

**Comment by Dengor1984** [comment]
Thanks for a good job and a fast fixes!)

Do you speak russian or ukrainian?

**Comment by acc-ua** [comment]
both

**Comment by acc-ua** [comment]
Ok, I have updated NPM so try to reinstall plugin ( npm install -g homebridge-xiaomi-humidifier )

**Comment by Deteorek** [comment]
Now everything works great! Thanks again for your hard work.

**Comment by Dengor1984** [comment]
Ще раз щиро дякую за чудовий плагін, сподіваюсь, що він не останній!)

**Comment by Dengor1984** [comment]
Чудовий плагін, працює як і треба, ще раз дякую!

Good plugin, works fine, thanks!

**Comment by acc-ua** [comment]
Радий допомогти :)  Оновлена версія плагіну буде коли вийде верcія ios 11.2, там вже буде підтримка типу прістрію Humidifier/Dehumidifer.

The new version of the plugin with support of Humidifier/Dehumidifier  device type will be once iOS 11.2 will be released.

**Comment by Dengor1984** [comment]
Доброго вечора!
Вже якось можна потестувати оновлений плагін з підтримкою зволожувача в хоукіт?

**Comment by acc-ua** [comment]
Ще не готовий, є деякі проблеми з телефоном (siri) після оновлення до 11.2

**Comment by leoneleone** [comment]
@acc-ua 
Has this issue been fixed? Is the plugin compatible with the latest version of miio?

**Comment by leoneleone** [comment]
https://github.com/acc-ua/homebridge-xiaomi-humidifier/pull/11
